//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_ID { get; set; }
        public int User_ID { get; set; }
        public double Total { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> Created_Time { get; set; }
    
        public virtual User User { get; set; }
    }
}
