//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }
        public int Product_ID { get; set; }
        [Required(ErrorMessage = "Product Name is required")]
        [StringLength(100, ErrorMessage = "Maximum length is 100 characters")]
        public string Product_Name { get; set; }
        [Required(ErrorMessage = "Description is required")]
        public String Description { get; set; }
        public int Category_ID { get; set; }
        [Range(1, 100000000, ErrorMessage = "Price must be greater than 0!")]
        public double? Price { get; set; }
        [Required(ErrorMessage = "Quantity is required")]
        [Range(1, 200, ErrorMessage = "Quantity must be greater than 0!")]
        public int Quantity { get; set; }
        public string Image { get; set; }
        [Range(0, 100, ErrorMessage = "Please input Percent of Discount from 0 to 100!")]
        public double? PercentOfDiscount { get; set; }
        [Range(0, 1)]
        public Nullable<int> Status { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Id_hobby { get; set; }
        public Nullable<int> Id_distrct { get; set; }
        public Product(int product_ID) { }
        public Product(int product_ID, string product_Name, String description, int category_ID, double? price, int quantity, string image, double? percentOfDiscount, int user_ID)
        {
            Product_ID = product_ID;
            Product_Name = product_Name;
            Description = description;
            Category_ID = category_ID;
            Price = price;
            Quantity = quantity;
            Image = image;
            PercentOfDiscount = percentOfDiscount;
            User_ID = user_ID;
        }
        public string Category_Name { get; set; }

        public Product(int product_ID, string product_Name, String description, string category_Name, double? price, int quantity, string image, double? percentOfDiscount)
        {
            Product_ID = product_ID;
            Product_Name = product_Name;
            Description = description;
            Category_Name = category_Name;
            Price = price;
            Quantity = quantity;
            Image = image;
            PercentOfDiscount = percentOfDiscount;
        }
        public Product(string product_Name, String description, int category_ID, double? price, int quantity, string image, double? percentOfDiscount)
        {
            Product_Name = product_Name;
            Description = description;
            Category_ID = category_ID;
            Price = price;
            Quantity = quantity;
            Image = image;
            PercentOfDiscount = percentOfDiscount;
        }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details> Order_Details { get; set; }
      
    }
}
