//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int Role_ID { get; set; }
        public string Role_Name { get; set; }
    }
}
