//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Orders = new HashSet<Order>();
        }

        string rex = "";
        public int User_ID { get; set; }
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please enter first name")]
        public string First_Name { get; set; }
        [Required(ErrorMessage = "Please enter last name")]
        public string Last_Name { get; set; }
        public int Role_ID { get; set; }
        [Required(ErrorMessage = "Please enter User Name")]
        public string Username { get; set; }
        [StringLength(32, MinimumLength = 4, ErrorMessage = "Độ dài mật khẩu ít nhất 4 ký tự.")]
        [Required(ErrorMessage = "Please enter Password")]
        public string Password { get; set; }
        [RegularExpression("^(0?)(3[2-9]|5[6|8|9]|7[0|6-9]|8[0-6|8|9]|9[0-4|6-9])[0-9]{7}$", ErrorMessage = "Please enter valid phone no.")]
        [Required(ErrorMessage = "Please enter Phone")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Please enter Address")]
        public string Address { get; set; }
        [Display(Name = "Email address")]
        [Required(ErrorMessage = "Please enter email")]
        [EmailAddress(ErrorMessage = "The email address is not valid")]
        public string Email { get; set; }
        public Boolean Status { get; set; }


        public User(int user_ID, string first_Name, string last_Name, int role_ID, string username, string password, string phone, string address, string email, bool status)
        {
            User_ID = user_ID;
            First_Name = first_Name;
            Last_Name = last_Name;
            Role_ID = role_ID;
            Username = username;
            Password = password;
            Phone = phone;
            Address = address;
            Status = status;
            Email = email;
        }
        public User(string username, string password)
        {
            Username = username;
            Password = password;
        }

        public string RoleName { get; set; }

        public User(int user_ID, string first_Name, string last_Name, string username, string password, string phone, string address, bool status, string email, string role)
        {
            User_ID = user_ID;
            First_Name = first_Name;
            Last_Name = last_Name;
            Username = username;
            Password = password;
            Phone = phone;
            Address = address;
            Status = status;
            RoleName = role;
            Email = email;
        }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
