//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Previews
    {
        public int Id { get; set; }
        public int Product_ID { get; set; }
        public int User_ID { get; set; }
        public int Rate { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Created_Time { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
